### ISSUE TITLE
Not working with latest Smack versions

### ISSUE THREAD

**Issue by FilipeMLFreitas** [Flowdalic/java-pinning#15]
Hello, 

This library is awesome and perfectly working for Smack 4.3.5, but it doesn't work for later versions.
It simply allows connections even though the pinning should fail.

**Comment by Flowdalic** [comment]
That would constitute the worst case outcome. Could you share a reproducer?

**Comment by FilipeMLFreitas** [comment]
Hello,

First, thank you for your work and ready response. Your work allows for secure connection for 300k users in our app.

Sorry I didn't include any code, I consider I'm doing it pretty basic.
Last working Smack version is 4.3.5, and higher versions it doesn't work.

Here is my smack 4.3.5 code:

`private aa (disregard this line, it's here otherwise the codes gets incorrectly formatted.. O_o


    private XMPPTCPConnectionConfiguration getConnectionConfiguration(String username, String password) throws Exception {
        SmackConfiguration.DEBUG = AppGlobal.XMPP_DEBUG;

        return XMPPTCPConnectionConfiguration.builder()
                .setUsernameAndPassword(username, password)
                .setXmppDomain(XMPP_SERVER_ADDRESS)
                .setHost(XMPP_SERVER_ADDRESS)
                .setCustomSSLContext(getSSLContext())
                .setSecurityMode(ConnectionConfiguration.SecurityMode.required)
                // check https://developer.android.com/reference/java/security/KeyStore for supported keystores
                .setKeystoreType("AndroidCAStore")
                .setKeystorePath(null)
                .setHostnameVerifier(new StrictHostnameVerifier()) //StrictHostnameVerifier is deprecated but safe for now
                .build();
    }

    private X509Certificate loadCertificate() throws Exception {
        CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
        InputStream certificateInput = new BufferedInputStream(Rrc1App.getAppContext().getAssets().open(CERTIFICATE_FILE_PREFIX + CERTIFICATE_FILE));
        return (X509Certificate) certificateFactory.generateCertificate(certificateInput);
    }

    public SSLContext getSSLContext() throws RuntimeException {
        try {
            // for convenience purpose, we load the public key from a certificate file, this way we don't hardcode the key somewhere
            // certificate expiry is not an issue
            X509Certificate certificate = loadCertificate();
            PlainPin plainPin = PlainPin.fromPublicKey(certificate.getPublicKey());
            // create an SSLContext for this public key pin
            return JavaPinning.forPins(Arrays.asList(plainPin));
        } catch (Exception e) {
            throw new RuntimeException("error while creating SSLContext", e);
        }
    }
`

Since for Smack 4.4.4 setCustomSSLContext() is deprecated, this is how I would have it:

`private aa (disregard this line, it's here otherwise the codes gets incorrectly formatted.. O_o
     
    private SslContextFactory sslContextFactory= this::getSSLContext;

    private XMPPTCPConnectionConfiguration getConnectionConfiguration(String username, String password) throws Exception {
        SmackConfiguration.DEBUG = AppGlobal.XMPP_DEBUG;

        return XMPPTCPConnectionConfiguration.builder()
                .setUsernameAndPassword(username, password)
                .setXmppDomain(XMPP_SERVER_ADDRESS)
                .setHost(XMPP_SERVER_ADDRESS)
                .setSslContextFactory(sslContextFactory)
                .setSecurityMode(ConnectionConfiguration.SecurityMode.required)
                // check https://developer.android.com/reference/java/security/KeyStore for supported keystores
                .setKeystoreType("AndroidCAStore")
                .setKeystorePath(null)
                .setHostnameVerifier(new StrictHostnameVerifier()) //StrictHostnameVerifier is deprecated but safe for now
                .build();
    }`

I've tried removing code and see it if works but still allows for connection:

`private aa (disregard this line, it's here otherwise the codes gets incorrectly formatted.. O_o
     
    private SslContextFactory sslContextFactory= this::getSSLContext;

    private XMPPTCPConnectionConfiguration getConnectionConfiguration(String username, String password) throws Exception {
        SmackConfiguration.DEBUG = AppGlobal.XMPP_DEBUG;

        return XMPPTCPConnectionConfiguration.builder()
                .setUsernameAndPassword(username, password)
                .setXmppDomain(XMPP_SERVER_ADDRESS)
                .setHost(XMPP_SERVER_ADDRESS)
                .setSslContextFactory(sslContextFactory)
                .setSecurityMode(ConnectionConfiguration.SecurityMode.required)
                .build();
    }`

Could you take a look? 

Thank you so much

**Comment by Flowdalic** [comment]
Have you tried attaching an debugger to see what happens?

**Comment by FilipeMLFreitas** [comment]
Good idea. 

For Smack 4.4.4, a silent exception is printed before a smack packet is printed:

`(disregard this line, it's here otherwise the codes gets incorrectly formatted.. O_o
 
    W/TLSUtils: Could not open default truststore at /system/lib/security/cacerts
    java.io.FileNotFoundException: /system/lib/security/cacerts: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:575)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at org.jivesoftware.smack.util.TLSUtils.getDefaultTruststoreStreamIfPossible(TLSUtils.java:269)
        at org.jivesoftware.smack.ConnectionConfiguration.getSmackTlsContext(ConnectionConfiguration.java:295)
        at org.jivesoftware.smack.ConnectionConfiguration.<init>(ConnectionConfiguration.java:191)
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration.<init>(XMPPTCPConnectionConfiguration.java:50)
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration.<init>(XMPPTCPConnectionConfiguration.java:36)
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration$Builder.build(XMPPTCPConnectionConfiguration.java:95)

        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7725)
        at libcore.io.IoBridge.open(IoBridge.java:561)
        at java.io.FileInputStream.<init>(FileInputStream.java:160) 
        at org.jivesoftware.smack.util.TLSUtils.getDefaultTruststoreStreamIfPossible(TLSUtils.java:269) 
        at org.jivesoftware.smack.ConnectionConfiguration.getSmackTlsContext(ConnectionConfiguration.java:295) 
        at org.jivesoftware.smack.ConnectionConfiguration.<init>(ConnectionConfiguration.java:191) 
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration.<init>(XMPPTCPConnectionConfiguration.java:50) 
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration.<init>(XMPPTCPConnectionConfiguration.java:36) 
        at org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration$Builder.build(XMPPTCPConnectionConfiguration.java:95) `´

After this this, the TLS packet is printed:

`I/System.out: 11:59:37 SENT (0): 
I/System.out: <stream:stream xmlns='jabber:client' to='' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='' xml:lang='en-US'>
I/System.out: 11:59:37 RECV (0): ?xml version='1.0' encoding='UTF-8'?>
I/System.out: <stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="" id="47r7fq5o4r" xml:lang="en-US" version="1.0">
I/System.out: 11:59:37 RECV (0): 
I/System.out: <stream:features>
I/System.out:   <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls">
I/System.out:   </starttls>
I/System.out:   <mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
I/System.out:     <mechanism>
I/System.out:       PLAIN
I/System.out:     </mechanism>
I/System.out:     <mechanism>
I/System.out:       SCRAM-SHA-1
I/System.out:     </mechanism>
I/System.out:     <mechanism>
I/System.out:       DIGEST-MD5
I/System.out:     </mechanism>
I/System.out:   </mechanisms>
I/System.out:   <ver xmlns="urn:xmpp:features:rosterver"/>
I/System.out: </stream:features>
I/System.out: 11:59:37 SENT (0): 
I/System.out: <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
I/System.out: 11:59:37 RECV (0): 
I/System.out: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>`

**Comment by Flowdalic** [comment]
I think there is even a work around, or (more) correct API usage, that can be used. Instead of

```java
SSLContext sc = JavaPinning
  .forPin("SHA256:e3b1812d945da1a2a2c5fa28029d2fe34c7c4142fb098f5cfedff1ff20e98781");
connectionConfiguration.setCustomSslContext(sc);
```

you do

```java
X509TrustManger tm = Java7Pinning.trustManagerForPin("SHA256:e3b1812d945da1a2a2c5fa28029d2fe34c7c4142fb098f5cfedff1ff20e98781");
connectionConfiguration.setCustomX509TrustManager(tm);
```

Please let me know if this works for you.

**Comment by FilipeMLFreitas** [comment]
Yes! It works! 
Thank you you so much, thank you for the taking the time to find a solution.
